[build.environment]
  YARN_VERSION = "1.12.1"
  NPM_VERSION = "6.4.1"

[build]
  command = "yarn build"
  publish = "dist"

[context.deploy-preview]
  command = "yarn build:preview"

[[redirects]]
  from = "/inscription"
  to = "https://www.helloasso.com/associations/alss-roller-skating/evenements/festi-loire-roller-2025"
  status = 302
  force = true
